export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"Home","i":"home","y":"h","r":{"minutes":0.38,"words":113}},["/index.html","/README.md"]],
  ["v-6516c560","/posts/01-new-beginning.html",{"t":"New Beginning","y":"a","e":"It's time for deploying a new blog!","a":"Lazy_V","d":"2022-11-27T00:00:00.000Z","l":"November 27, 2022","c":["Jottings"],"g":["Jottings"],"u":true,"r":{"minutes":0.44,"words":131}},["/posts/01-new-beginning","/posts/01-new-beginning.md"]],
  ["v-2d0ad528","/zh/",{"t":"主页","i":"home","y":"h","r":{"minutes":0.58,"words":175}},["/zh/index.html","/zh/README.md"]],
  ["v-3cb9fdd1","/zh/posts/01-new-beginning.html",{"t":"新的开始","y":"a","e":"是时候部署一个新的博客了！","a":"Lazy_V","d":"2022-11-27T00:00:00.000Z","l":"2022年11月27日","c":["随笔"],"g":["随笔"],"u":true,"r":{"minutes":0.62,"words":186}},["/zh/posts/01-new-beginning","/zh/posts/01-new-beginning.md"]],
  ["v-3706649a","/404.html",{"t":"","y":"p"},["/404"]],
  ["v-5bc93818","/category/",{"t":"Category","y":"p"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"t":"Tag","y":"p"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"t":"Articles","y":"p"},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"t":"Encrypted","y":"p"},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"t":"Slides","y":"p"},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"t":"Star","y":"p"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"t":"Timeline","y":"p"},["/timeline/index.html"]],
  ["v-01310501","/category/jottings/",{"t":"Jottings Category","y":"p"},["/category/jottings/index.html"]],
  ["v-46ce578b","/tag/jottings/",{"t":"Jottings Tag","y":"p"},["/tag/jottings/index.html"]],
  ["v-54d7ff21","/zh/article/",{"t":"文章","y":"p"},["/zh/article/index.html"]],
  ["v-1ad78213","/zh/encrypted/",{"t":"加密","y":"p"},["/zh/encrypted/index.html"]],
  ["v-5b30cfc6","/zh/slide/",{"t":"幻灯片","y":"p"},["/zh/slide/index.html"]],
  ["v-2c3ee7f5","/zh/star/",{"t":"收藏","y":"p"},["/zh/star/index.html"]],
  ["v-27b02be6","/zh/timeline/",{"t":"时间轴","y":"p"},["/zh/timeline/index.html"]],
  ["v-fbb94a6e","/zh/category/",{"t":"分类","y":"p"},["/zh/category/index.html"]],
  ["v-540234fd","/zh/tag/",{"t":"标签","y":"p"},["/zh/tag/index.html"]],
  ["v-7d286fb5","/zh/category/%E9%9A%8F%E7%AC%94/",{"t":"随笔 分类","y":"p"},["/zh/category/随笔/","/zh/category/%E9%9A%8F%E7%AC%94/index.html"]],
  ["v-60123dfe","/zh/tag/%E9%9A%8F%E7%AC%94/",{"t":"随笔 标签","y":"p"},["/zh/tag/随笔/","/zh/tag/%E9%9A%8F%E7%AC%94/index.html"]],
]
