name: Build and Deploy
on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '18'

      # 安装依赖
      - name: Install dependencies
        run: npm ci

      # 解决内存不足的问题
      - name: Fix low memory
        run: npm install -g increase-memory-limit && increase-memory-limit

      # 运行构建脚本
      - name: Build VuePress site
        run: npm run docs:build

      # 修复 GitHub Pages 不识别下划线开头文件的问题
      - name: Post Fix GitHub Pages
        run: touch src/.vuepress/dist/.nojekyll

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 pages 分支
          target_branch: pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: src/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}